# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [6]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
#print(np.round( A@B   ,2)), print(' ')
#print(np.round( A@C   ,2)), print(' ')
#print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 1.65  0.11 -0.62 -0.51]
 [ 0.64 -2.83 -0.5  -0.28]
 [ 0.63  0.16 -0.37 -0.32]
 [ 1.46 -0.13 -0.02  0.05]
 [-0.73 -0.39  1.34  1.23]
 [ 1.73  0.81  1.6   1.5 ]
 [ 0.1   1.61  0.22  0.12]]


# Using pytorch

In [12]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
#print(np.round( A@B   ,2)), print(' ')
#print(np.round( A@B.T ,2)), print(' ')
#print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-1.9400,  2.1000,  0.3100,  0.3200, -2.3100,  0.6900, -1.8100],
        [ 1.2600,  1.9800, -0.2000,  1.9900, -2.8900,  1.4500,  2.5200],
        [ 1.9700, -0.8600, -0.5900,  1.6100,  2.2400,  0.6600,  2.3200]])
